### PR TITLE
update reading/writing in Transfer logic 

### PR DESCRIPTION
**Pull request by cssivision**

### CODE REVIEW

**Comment by cssivision** [comment]
for personal usage, i prefer use `tokio_io::io::copy` for proxying of data, but this implemented through a manual implementation of `Future`, shows how it's easy to transition back and forth between the `Future` and tokio-io`'s combinators`.

**Comment by alexcrichton** [comment]
Thanks for the PR! The "one global buffer" though was sort of the motivational factor for this server, so having a buffer-per-connection sort of defeats the purpose of that :(

**Comment by cssivision** [comment]
@alexcrichton ok, i will fix this.

**Comment by alexcrichton** [comment]
hm I don't think this works if multiple connections are using the same buffer? It looks like they'll just stomp over each other if the data's only partially written out?

**Comment by cssivision** [comment]
yes, write in this way, can not use a global buffer, so i close this, if i have new ideas, i will reopen this.

**Pull request closed without merging**
